# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

common_params:
  - &test_collector_common_params
    files: "*.xml"
    format: "junit"

agents:
  queue: "android"

steps:
  #################
  # Gradle Wrapper Validation
  #################
  - label: Gradle Wrapper Validation
    command: validate_gradle_wrapper
    agents:
      queue: linter

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "🧪 Tests"
    command: ./gradlew test
    plugins:
      - $CI_TOOLKIT
      - $TEST_COLLECTOR:
          <<: *test_collector_common_params
          api-token-env-name: "BUILDKITE_TEST_SUITE_API_TOKEN"
    artifact_paths:
      - "**/build/test-results/**/*.xml"
    notify:
      - github_commit_status:
          context: Tests

  - label: "🧰 Build CLI"
    command: ./gradlew :event-horizon-cli:nativeCompile -Dorg.graalvm.buildargs=--initialize-at-build-time
    plugins:
      - docker#v5.13.0:
          image: ghcr.io/graalvm/graalvm-community:21
          mount-buildkite-agent: true
    artifact_paths:
      - "event-horizon-cli/build/native/nativeCompile/event-horizon-cli"
