# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

common_params:
  - &test_collector_common_params
    files: "*.xml"
    format: "junit"

agents:
  queue: "android"

steps:

  - label: "Test homebrew install"
    plugins:
      - docker#v5.13.0:
          image: homebrew/brew
          platform: linux/amd64
    command: |
      brew tap automattic/build-tools && brew install automattic/build-tools/event-horizon && event-horizon --help

